# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [3]:
import pandas as pd

df = pd.read_csv("students.csv")
df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 🔢 2. Sorting Data

In [4]:
# Sort by math_score
df.sort_values(by="math_score")

     first_name  last_name  math_score  science_score
28      Melanie      Baker          60             94
2        Joshua      Adams          61            100
19         Adam      Adams          61             70
13        James      Cohen          61             66
12      Anthony    Hawkins          62             74
44  Christopher      Brown          62             64
14        Debra    Cameron          65             84
9       Anthony       Gray          65             74
37    Christine      Hicks          65             80
49      Michael   Valencia          65             91
39      Barbara   Williams          66             74
36        Maria     Bright          66             74
7   Christopher     Daniel          66             64
1         Angel      Clark          67             78
47       Joshua       Rice          67             80
6      Patricia    Jackson          68             72
33       Teresa      Hurst          69             77
29    Cassandra     Wright          70             75
21        Helen       Hahn          72             82
34     Nicholas       Ross          73            100
15          Amy    Parsons          73             77
5         Erica      Lynch          74             96
24        Susan       Rios          74             64
16      Jeffrey      Perez          74             89
4          Jill       Wong          75             83
43        Keith  Henderson          76             77
27        Colin      Ellis          77             70
3       Jeffrey     Zuniga          77             99
32       Amanda   Richards          77             84
35       Andrea   Robinson          81             95
31      Jessica      Baker          81             89
41      Brandon     Burton          82             80
40        Janet  Rodriguez          82             62
38     Michelle      Davis          84             63
48      Cynthia     Maddox          84             73
23         Eric    Edwards          86             77
30      Lindsay    Hoffman          87             70
11      William     Bowman          87             65
25      Matthew     Foster          88             98
45        Jesse      James          89             73
17      Bridget    Johnson          92            100
46        Craig    Ferrell          94             96
22      Matthew     Walter          94             73
8        Robert     Martin          94             62
20        Linda      Clark          95             83
26  Christopher      Rocha          97            100
10      Jeffery       Mayo          97             78
18         Lisa    Stewart          98             83
42       Jeremy     Conner          98             85
0      Danielle       Wood         100             95

In [5]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

     first_name  last_name  math_score  science_score
17      Bridget    Johnson          92            100
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
46        Craig    Ferrell          94             96
5         Erica      Lynch          74             96
0      Danielle       Wood         100             95
35       Andrea   Robinson          81             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
31      Jessica      Baker          81             89
16      Jeffrey      Perez          74             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
20        Linda      Clark          95             83
18         Lisa    Stewart          98             83
21        Helen       Hahn          72             82
41      Brandon     Burton          82             80
47       Joshua       Rice          67             80
37    Christine      Hicks          65             80
10      Jeffery       Mayo          97             78
1         Angel      Clark          67             78
43        Keith  Henderson          76             77
33       Teresa      Hurst          69             77
23         Eric    Edwards          86             77
15          Amy    Parsons          73             77
29    Cassandra     Wright          70             75
39      Barbara   Williams          66             74
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
48      Cynthia     Maddox          84             73
22      Matthew     Walter          94             73
45        Jesse      James          89             73
6      Patricia    Jackson          68             72
30      Lindsay    Hoffman          87             70
19         Adam      Adams          61             70
27        Colin      Ellis          77             70
13        James      Cohen          61             66
11      William     Bowman          87             65
24        Susan       Rios          74             64
7   Christopher     Daniel          66             64
44  Christopher      Brown          62             64
38     Michelle      Davis          84             63
8        Robert     Martin          94             62
40        Janet  Rodriguez          82             62

In [6]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

     first_name  last_name  math_score  science_score
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
17      Bridget    Johnson          92            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
5         Erica      Lynch          74             96
46        Craig    Ferrell          94             96
35       Andrea   Robinson          81             95
0      Danielle       Wood         100             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
16      Jeffrey      Perez          74             89
31      Jessica      Baker          81             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
20        Linda      Clark          95             83
18         Lisa    Stewart          98             83
21        Helen       Hahn          72             82
37    Christine      Hicks          65             80
47       Joshua       Rice          67             80
41      Brandon     Burton          82             80
1         Angel      Clark          67             78
10      Jeffery       Mayo          97             78
33       Teresa      Hurst          69             77
15          Amy    Parsons          73             77
43        Keith  Henderson          76             77
23         Eric    Edwards          86             77
29    Cassandra     Wright          70             75
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
48      Cynthia     Maddox          84             73
45        Jesse      James          89             73
22      Matthew     Walter          94             73
6      Patricia    Jackson          68             72
19         Adam      Adams          61             70
27        Colin      Ellis          77             70
30      Lindsay    Hoffman          87             70
13        James      Cohen          61             66
11      William     Bowman          87             65
44  Christopher      Brown          62             64
7   Christopher     Daniel          66             64
24        Susan       Rios          74             64
38     Michelle      Davis          84             63
40        Janet  Rodriguez          82             62
8        Robert     Martin          94             62

### 🧪 3. Filtering with Conditions

In [7]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
8        Robert    Martin          94             62
10      Jeffery      Mayo          97             78
17      Bridget   Johnson          92            100
18         Lisa   Stewart          98             83
20        Linda     Clark          95             83
22      Matthew    Walter          94             73
26  Christopher     Rocha          97            100
42       Jeremy    Conner          98             85
46        Craig   Ferrell          94             96

In [8]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

     first_name  last_name  math_score  science_score
1         Angel      Clark          67             78
2        Joshua      Adams          61            100
6      Patricia    Jackson          68             72
7   Christopher     Daniel          66             64
8        Robert     Martin          94             62
9       Anthony       Gray          65             74
11      William     Bowman          87             65
12      Anthony    Hawkins          62             74
13        James      Cohen          61             66
14        Debra    Cameron          65             84
19         Adam      Adams          61             70
24        Susan       Rios          74             64
28      Melanie      Baker          60             94
33       Teresa      Hurst          69             77
36        Maria     Bright          66             74
37    Christine      Hicks          65             80
38     Michelle      Davis          84             63
39      Barbara   Williams          66             74
40        Janet  Rodriguez          82             62
44  Christopher      Brown          62             64
47       Joshua       Rice          67             80
49      Michael   Valencia          65             91

### 🔗 4. Combining Filters

In [9]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧾 5. Using `.query()` for Readability

In [10]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [11]:
# Sort the dataset by first name alphabetically
df.sort_values(by="first_name")

     first_name  last_name  math_score  science_score
19         Adam      Adams          61             70
32       Amanda   Richards          77             84
15          Amy    Parsons          73             77
35       Andrea   Robinson          81             95
1         Angel      Clark          67             78
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
39      Barbara   Williams          66             74
41      Brandon     Burton          82             80
17      Bridget    Johnson          92            100
29    Cassandra     Wright          70             75
37    Christine      Hicks          65             80
44  Christopher      Brown          62             64
26  Christopher      Rocha          97            100
7   Christopher     Daniel          66             64
27        Colin      Ellis          77             70
46        Craig    Ferrell          94             96
48      Cynthia     Maddox          84             73
0      Danielle       Wood         100             95
14        Debra    Cameron          65             84
23         Eric    Edwards          86             77
5         Erica      Lynch          74             96
21        Helen       Hahn          72             82
13        James      Cohen          61             66
40        Janet  Rodriguez          82             62
10      Jeffery       Mayo          97             78
16      Jeffrey      Perez          74             89
3       Jeffrey     Zuniga          77             99
42       Jeremy     Conner          98             85
45        Jesse      James          89             73
31      Jessica      Baker          81             89
4          Jill       Wong          75             83
2        Joshua      Adams          61            100
47       Joshua       Rice          67             80
43        Keith  Henderson          76             77
20        Linda      Clark          95             83
30      Lindsay    Hoffman          87             70
18         Lisa    Stewart          98             83
36        Maria     Bright          66             74
25      Matthew     Foster          88             98
22      Matthew     Walter          94             73
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
38     Michelle      Davis          84             63
34     Nicholas       Ross          73            100
6      Patricia    Jackson          68             72
8        Robert     Martin          94             62
24        Susan       Rios          74             64
33       Teresa      Hurst          69             77
11      William     Bowman          87             65

In [15]:
# Find students with the same math and science score
df[(df["math_score"]) == (df["science_score"])]

Empty DataFrame
Columns: [first_name, last_name, math_score, science_score]
Index: []

In [14]:
# Use .query() to find students who scored over 95 in either subject
df.query("math_score > 95 or science_score > 95")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
2        Joshua     Adams          61            100
3       Jeffrey    Zuniga          77             99
5         Erica     Lynch          74             96
10      Jeffery      Mayo          97             78
17      Bridget   Johnson          92            100
18         Lisa   Stewart          98             83
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
34     Nicholas      Ross          73            100
42       Jeremy    Conner          98             85
46        Craig   Ferrell          94             96

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |